# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c85f0511004940d07fd1139e13efb10bb2ce3b53817d3ccb991a7417e310745cb68707f3701e7c318dabfae9b3ed43ac915688705dcd1a0cd958a86da6eb4746

test:
  secret_key_base: 9507fb2fdc427e78c5a17ab8249bb41c366ec0cf405d2b6359c951f7f7ac05be102c97dcdee7899b7f8e0234126efea6ff4f9e6e87de4edffc73872a6b7c853f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
